# Generated by Django 4.0.4 on 2022-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_p_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_photo',
            field=models.ImageField(blank=True, null=True, upload_to='p_images/'),
        ),
    ]
