# Generated by Django 4.1 on 2022-08-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('q_date', models.DateTimeField(verbose_name='data published')),
                ('q_photo', models.ImageField(blank=True, null=True, upload_to='q_images/')),
                ('hashtags', models.ManyToManyField(blank=True, to='QnA.hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('qna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='QnA.qna')),
            ],
        ),
    ]
